<a href="https://colab.research.google.com/github/htetlwink/AIProjectTest/blob/main/ProjectTestBook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Import Libries

In [ ]:
import sklearn
import numpy as np
import pandas as pd
import tensorflow as tf
#from google.colab import drive
import pickle

### GPU Check

In [ ]:
device_name = tf.test.gpu_device_name()
if device_name != '/device:GPU:0':
  raise SystemError("GPU device not found")
print("Found GPU at: {}".format(device_name))

Found GPU at: /device:GPU:0


# Data Understanding

### Load the Data From Drive

In [ ]:
#from google.colab import drive
#drive.mount("/content/drive")

In [ ]:
dataset = pd.read_csv("https://raw.githubusercontent.com/htetlwink/AIProjectTest/main/dataset/makeupdataset.csv")

### Data Understanding

Check the dataset shape

In [ ]:
dataset.shape

(172, 13)

Check the dataset columns

In [ ]:
dataset.columns

Index(['Hex_Code', 'R', 'G', 'B', 'Core_Skin_Type', 'Skin_Type', 'Core_Color',
       'Foundation_Color', 'Blush_Color', 'Lipstick_Color', 'Eyeshadow_Color',
       'Highlighter_Color', 'Contour_Color'],
      dtype='object')

Check the dataset brief

In [ ]:
dataset.head()

Hex_Code    R    G    B Core_Skin_Type    Skin_Type Core_Color  \
0  #FFFAFA  255  250  250           Oily         Oily       Pale   
1  #FFF0E1  255  240  225            Dry          Dry       Pale   
2  #FAE7D3  250  231  211    Combination  Combination       Pale   
3  #F0D5BE  240  213  190      Sensitive    Sensitive       Pale   
4  #D8B998  216  185  152    Combination       Normal    Natural   

  Foundation_Color Blush_Color Lipstick_Color Eyeshadow_Color  \
0        Alabaster   Soft Pink      Nude Pink       Champagne   
1        Porcelain  Light Pink      Nude Pink       Champagne   
2            Ivory   Pale Pink     Soft Coral       Soft Gold   
3      Light Beige  Soft Coral     Soft Coral       Soft Gold   
4       Warm Beige       Peach     Soft Coral       Soft Gold   

  Highlighter_Color Contour_Color  
0             Pearl    Soft Taupe  
1             Pearl    Soft Taupe  
2         Soft Gold    Soft Taupe  
3         Soft Gold    Warm Beige  
4         Soft Gold    Warm Beige

Check How many Skin Type and MakeUp Shade in the dataset

In [ ]:
dataset["Core_Skin_Type"].value_counts()

Core_Skin_Type
Dry            78
Oily           35
Sensitive      33
Combination    26
Name: count, dtype: int64

In [ ]:
dataset["Core_Color"].value_counts()

Core_Color
Mocha      74
Natural    58
Pale       24
Golden     16
Name: count, dtype: int64

Check the dataset information

In [ ]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 172 entries, 0 to 171
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype 
---  ------             --------------  ----- 
 0   Hex_Code           172 non-null    object
 1   R                  172 non-null    int64 
 2   G                  172 non-null    int64 
 3   B                  172 non-null    int64 
 4   Core_Skin_Type     172 non-null    object
 5   Skin_Type          172 non-null    object
 6   Core_Color         172 non-null    object
 7   Foundation_Color   172 non-null    object
 8   Blush_Color        172 non-null    object
 9   Lipstick_Color     172 non-null    object
 10  Eyeshadow_Color    172 non-null    object
 11  Highlighter_Color  172 non-null    object
 12  Contour_Color      172 non-null    object
dtypes: int64(3), object(10)
memory usage: 17.6+ KB


# Data Processing

In [ ]:
dataset.columns

Index(['Hex_Code', 'R', 'G', 'B', 'Core_Skin_Type', 'Skin_Type', 'Core_Color',
       'Foundation_Color', 'Blush_Color', 'Lipstick_Color', 'Eyeshadow_Color',
       'Highlighter_Color', 'Contour_Color'],
      dtype='object')

Remove the Hex Column because we don't need them

In [ ]:
dataset = dataset.drop(columns=["Hex_Code","Skin_Type","Foundation_Color","Blush_Color","Lipstick_Color","Eyeshadow_Color","Highlighter_Color","Contour_Color"])
dataset.head()

R    G    B Core_Skin_Type Core_Color
0  255  250  250           Oily       Pale
1  255  240  225            Dry       Pale
2  250  231  211    Combination       Pale
3  240  213  190      Sensitive       Pale
4  216  185  152    Combination    Natural

Shuffle the dataset

In [ ]:
dataset = dataset.sample(frac=1)
dataset.head()

R    G    B Core_Skin_Type Core_Color
141  139    0    0      Sensitive      Mocha
44   192  142   98    Combination    Natural
56   184  134   11      Sensitive    Natural
100   92   64   51      Sensitive      Mocha
127  255  228  196            Dry    Natural

Convert String data types to interger inorder to fit in model

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
dataset["Core_Skin_Type"] = le.fit_transform(dataset["Core_Skin_Type"])
dataset["Core_Color"] = le.fit_transform(dataset["Core_Color"])

Download Encoder Setting

In [ ]:
with open('Skin_Type_encoder.pkl', 'wb') as file:
    pickle.dump(le, file)

In [ ]:
dataset.head()

R    G    B  Core_Skin_Type  Core_Color
141  139    0    0               3           1
44   192  142   98               0           2
56   184  134   11               3           2
100   92   64   51               3           1
127  255  228  196               1           2

In [ ]:
Xvalue = dataset.iloc[:,:-1]
Yvalue = dataset.iloc[:,-1]

Split the dataset into 80% train data and 20 % test data

In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(Xvalue,Yvalue, test_size=0.2, random_state=42)

#Model Fit

In [ ]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(x_train, y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

# Save/Load Model

Save the Model with Pickle Module

In [ ]:
#import pickle
with open('Trained_model.pkl', 'wb') as file:
    pickle.dump(model, file)


Load the Model with Pickle Module

In [ ]:
#import pickle
with open('Trained_model.pkl', 'rb') as file:
    model = pickle.load(file)

#Model Prediction

In [ ]:
y_pred = model.predict(x_test)

Confusion Matrix

In [ ]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, y_pred))

[[ 0  2  2  0]
 [ 0 11  2  0]
 [ 0  4  7  4]
 [ 0  0  1  2]]


Result

In [ ]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
print(accuracy_score(y_test, y_pred)*100,"%")
print(precision_score(y_test, y_pred, average = "macro")*100,"%")
print(recall_score(y_test, y_pred, average = "macro")*100,"%")
print(f1_score(y_test, y_pred, average = "macro")*100,"%")

57.14285714285714 %
39.09313725490196 %
49.48717948717949 %
42.40740740740741 %


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


#User Input and Testing

Input Data in Array [Skin Type, R, G, B]

In [ ]:
custom_data = np.array([[255,116,145,3]])

In [ ]:
prediction = model.predict(custom_data)
makeuptype = le.inverse_transform(prediction)
print(f"You Should Use {makeuptype}")

You Should Use ['Mocha']


/usr/local/lib/python3.10/dist-packages/sklearn/base.py:465: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(
